# Stage 1: Сборка Maven-проекта
FROM maven:3.9.9-eclipse-temurin-11 AS consumer_builder

WORKDIR /app
COPY . .
# Переходим в папку consumer
# WORKDIR /app/consumer
# RUN ls -l
RUN mvn clean package -DskipTests
# RUN ls -la target

# Stage 2: Запуск приложения
FROM openjdk:11-jre-slim
RUN apt-get update && \
    apt-get install -y wget ca-certificates curl jq && \
    mkdir -p /usr/local/share/ca-certificates/Yandex && \
    wget "https://storage.yandexcloud.net/cloud-certs/CA.pem" \
         --output-document /usr/local/share/ca-certificates/Yandex/YandexInternalRootCA.crt && \
    chmod 0655 /usr/local/share/ca-certificates/Yandex/YandexInternalRootCA.crt && \
    update-ca-certificates && \
    keytool -importcert -alias YandexCA \
            -file /usr/local/share/ca-certificates/Yandex/YandexInternalRootCA.crt \
            -keystore /etc/security/ssl \
            -storepass kafkaSuperPuper \
            -noprompt
WORKDIR /app

# RUN ls -la /app/target
COPY --from=consumer_builder /app/consumer/target/kafka-java-project-1.0-SNAPSHOT-consumer.jar /app/kafka-consumer.jar



# COPY Product.avsc /app/Product.avsc
# COPY entrypoint.sh /app/entrypoint.sh
# RUN chmod +x /app/entrypoint.sh
# ENTRYPOINT ["/app/entrypoint.sh"]
CMD ["java", "-jar", "/app/kafka-consumer.jar"]
