# Stage 1: Сборка Maven-проекта
FROM maven:3.9.9-eclipse-temurin-11 AS consumer_builder

WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests


# Stage 2: Запуск приложения
FROM openjdk:11-jre-slim
RUN apt-get update && \
    apt-get install -y wget ca-certificates curl jq && \
    mkdir -p /usr/local/share/ca-certificates/Yandex && \
    wget "https://storage.yandexcloud.net/cloud-certs/CA.pem" \
         --output-document /usr/local/share/ca-certificates/Yandex/YandexInternalRootCA.crt && \
    chmod 0655 /usr/local/share/ca-certificates/Yandex/YandexInternalRootCA.crt && \
    update-ca-certificates && \
    keytool -importcert -alias YandexCA \
            -file /usr/local/share/ca-certificates/Yandex/YandexInternalRootCA.crt \
            -keystore /etc/security/ssl \
            -storepass kafkaSuperPuper \
            -noprompt
WORKDIR /app

COPY --from=consumer_builder /app/consumer/target/kafka-java-project-1.0-SNAPSHOT-consumer.jar /app/kafka-consumer.jar

CMD ["java", "-jar", "/app/kafka-consumer.jar"]
